title: Fast 3D object detection and camera localization with stereo event camera
description: (The page is an overview of this library).
show_downloads: false
google_analytics: true
theme: jekyll-theme-tactile